name: provider docs build
on:
  repository_dispatch:
    types:
      - provider
jobs:
  provider-docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo }}
