name: provider docs build
on:
  repository_dispatch:
    types:
      - provider
jobs:
  provider-docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: pulumi/pulumi
          path: pulumi
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo }}
          ref: ${{ github.event.client_payload.ref }}
          path: ${{ github.event.client_payload.project }}
      - run: ls -alh ${{ github.workspace }}
      - uses: actions/setup-go@v2
      - uses: actions/setup-node@v2-beta
      - uses: actions/setup-python@v2
      - uses: actions/setup-dotnet@v1
      - run: make ensure ensure_tools
      - name: run typedoc
        run: PKGS=${{ github.event.client_payload.repo }} NOBUILD=true ./scripts/run_typedoc.sh
      - name: generate resource docs
        run: ./scripts/gen_resource_docs.sh "${{ github.event.client_payload.repo }}" true "${{ github.event.client_payload.ref }}"
      - name: generate python docs
        run: ./scripts/generate_python_docs.sh "${{ github.event.client_payload.repo }}"
      - name: git status
        run: git status && git diff
